services:
  app:
    build: .
    container_name: laravel-app
    restart: unless-stopped
    ports:
      - "5173:5173"
    volumes:
      - .:/var/www
    environment:
      - VITE_HOST=0.0.0.0

  nginx:
    image: nginx:stable-alpine
    container_name: laravel-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
